# Generated by Django 2.2.1 on 2019-08-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
